// Render-only settings; intentionally no include guard (DDNet X-macros).
MACRO_CONFIG_INT(PrismAtmosphere, prism_atmosphere, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable world atmosphere (OpenGL 3.3+)")
MACRO_CONFIG_INT(PrismAtmospherePreset, prism_atmosphere_preset, 0, 0, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "0 Off, 1 Subtle, 2 Cinematic, 3 Vivid, 4 Custom; use prism_atmosphere_preset")
MACRO_CONFIG_INT(PrismExposure, prism_exposure, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Exposure in hundredths of a stop")
MACRO_CONFIG_INT(PrismContrast, prism_contrast, 100, 0, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Contrast percent")
MACRO_CONFIG_INT(PrismSaturation, prism_saturation, 100, 0, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Saturation percent")
MACRO_CONFIG_INT(PrismGamma, prism_gamma, 100, 25, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gamma percent")
MACRO_CONFIG_INT(PrismHighlights, prism_highlights, 0, -100, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight adjustment percent")
MACRO_CONFIG_INT(PrismShadows, prism_shadows, 0, -100, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shadow adjustment percent")
MACRO_CONFIG_INT(PrismBloomStrength, prism_bloom_strength, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bloom strength percent")
MACRO_CONFIG_INT(PrismBloomThreshold, prism_bloom_threshold, 80, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bloom luminance threshold percent")
MACRO_CONFIG_INT(PrismBloomRadius, prism_bloom_radius, 4, 1, 32, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bloom sample radius in screen pixels")
MACRO_CONFIG_INT(PrismVignette, prism_vignette, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vignette percent")
MACRO_CONFIG_INT(PrismTintStrength, prism_tint_strength, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tint percent; multiplied by tint alpha")
MACRO_CONFIG_INT(PrismPlayerGlow, prism_player_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable player aura")
MACRO_CONFIG_INT(PrismGlowLocal, prism_glow_local, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura on controlled player")
MACRO_CONFIG_INT(PrismGlowOthers, prism_glow_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura on other visible players")
MACRO_CONFIG_INT(PrismGlowDummy, prism_glow_dummy, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura on connected dummy")
MACRO_CONFIG_INT(PrismGlowIntensity, prism_glow_intensity, 100, 0, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura intensity percent")
MACRO_CONFIG_INT(PrismGlowRadius, prism_glow_radius, 48, 8, 192, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura radius in world units")
MACRO_CONFIG_INT(PrismGlowAlpha, prism_glow_alpha, 25, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura opacity percent")
MACRO_CONFIG_INT(PrismGlowSoftness, prism_glow_softness, 200, 25, 800, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura falloff exponent in hundredths")
MACRO_CONFIG_INT(PrismGlowColorMode, prism_glow_color_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aura color: 0 accent, 1 entity body, 2 custom")
MACRO_CONFIG_COL(PrismAtmosphereTint, prism_atmosphere_tint, 4278190335u, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Atmosphere tint (HSLA)")
MACRO_CONFIG_COL(PrismGlowColor, prism_glow_color, 4278190335u, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Player aura color (HSLA)")
