// Prism Assist configuration. No include guard: consumed by DDNet config X-macros.
MACRO_CONFIG_INT(PrismTriggerEnabled, prism_trigger_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trigger when manual aim intersects a visible target")
MACRO_CONFIG_INT(PrismTriggerAction, prism_trigger_action, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trigger action: fire or hook")
MACRO_CONFIG_INT(PrismTriggerTolerance, prism_trigger_tolerance, 2, 0, 15, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim angular tolerance in degrees")
MACRO_CONFIG_INT(PrismTriggerRange, prism_trigger_range, 500, 64, 1200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum trigger target distance")
MACRO_CONFIG_INT(PrismTriggerPrediction, prism_trigger_prediction, 0, 0, 12, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target motion prediction in ticks")
MACRO_CONFIG_INT(PrismTriggerCooldown, prism_trigger_cooldown, 6, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Minimum ticks between trigger actions")
MACRO_CONFIG_INT(PrismTriggerDebug, prism_trigger_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show trigger ray, target, and alignment")
MACRO_CONFIG_INT(PrismFreezeAvoid, prism_freeze_avoid, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeze Avoid: off, warning, assist")
MACRO_CONFIG_INT(PrismFreezeHorizon, prism_freeze_horizon, 12, 4, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeze Avoid lookahead in ticks")
MACRO_CONFIG_INT(PrismFreezeDebug, prism_freeze_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Freeze Avoid trajectory debug")
