// Prism Solo Pathfinder configuration. DDNet config X-macros; no include guard.
MACRO_CONFIG_INT(PrismSoloEnabled, prism_solo_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Solo Pathfinder")
MACRO_CONFIG_INT(PrismSoloMode, prism_solo_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Solo Pathfinder: 0 Assist, 1 Autopilot")
MACRO_CONFIG_INT(PrismSoloTarget, prism_solo_target, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Solo Pathfinder destination: 0 Finish, 1 Manual")
MACRO_CONFIG_INT(PrismSoloTargetX, prism_solo_target_x, 0, 0, 1000000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Manual destination X in world units")
MACRO_CONFIG_INT(PrismSoloTargetY, prism_solo_target_y, 0, 0, 1000000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Manual destination Y in world units")
MACRO_CONFIG_INT(PrismSoloBudget, prism_solo_budget, 2000, 500, 8000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Resumable planner budget per input tick in microseconds")
MACRO_CONFIG_INT(PrismSoloHorizon, prism_solo_horizon, 100, 24, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Physical search horizon in ticks")
MACRO_CONFIG_INT(PrismSoloThreshold, prism_solo_threshold, 20, 4, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Replan position divergence in world units")
MACRO_CONFIG_INT(PrismSoloSafe, prism_solo_safe, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prefer robust corridors when route costs are similar")
MACRO_CONFIG_INT(PrismSoloMomentum, prism_solo_momentum, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Preserve useful velocity during physical search")
MACRO_CONFIG_INT(PrismSoloOverride, prism_solo_override, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pause Autopilot immediately on manual movement, jump, hook or fire")
MACRO_CONFIG_INT(PrismSoloRoute, prism_solo_route, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw global corridor and immediate destination")
MACRO_CONFIG_INT(PrismSoloPrediction, prism_solo_prediction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw selected physical trajectory and landing")
MACRO_CONFIG_INT(PrismSoloHooks, prism_solo_hooks, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw hook anchor candidates")
MACRO_CONFIG_INT(PrismSoloDebug, prism_solo_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw bounded search candidates and state details")
MACRO_CONFIG_INT(PrismSoloLog, prism_solo_log, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Log planner state changes and rejection counts")
MACRO_CONFIG_INT(PrismSoloHud, prism_solo_hud, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Solo Pathfinder status widget")
MACRO_CONFIG_INT(PrismSoloHudX, prism_solo_hud_x, 7000, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pathfinder widget horizontal position")
MACRO_CONFIG_INT(PrismSoloHudY, prism_solo_hud_y, 1200, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pathfinder widget vertical position")
