// Render-only Prism effects. Intentionally no include guard: DDNet X-macro configuration.
MACRO_CONFIG_INT(PrismEffectQuality, prism_effect_quality, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cosmetic budget: 0 low, 1 medium, 2 high")
MACRO_CONFIG_INT(PrismHookEffect, prism_hook_effect, 0, 0, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook effect: 0 none, 1 leaves, 2 sparkles, 3 hearts, 4 pulsation")
MACRO_CONFIG_INT(PrismHookEffectLocal, prism_hook_effect_local, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show local hook effects")
MACRO_CONFIG_INT(PrismHookEffectOthers, prism_hook_effect_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show other visible hook effects")
MACRO_CONFIG_INT(PrismHookParticleCap, prism_hook_particle_cap, 256, 0, 512, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Global hook particle count limit")
MACRO_CONFIG_INT(PrismHookParticleRate, prism_hook_particle_rate, 24, 1, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Particles per hook per second")
MACRO_CONFIG_INT(PrismHookParticleSize, prism_hook_particle_size, 6, 1, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook particle size in world units")
MACRO_CONFIG_INT(PrismHookParticleSpeed, prism_hook_particle_speed, 20, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook particle speed")
MACRO_CONFIG_INT(PrismHookParticleLifetime, prism_hook_particle_lifetime, 800, 100, 3000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook particle lifetime in milliseconds")
MACRO_CONFIG_INT(PrismHookParticleOpacity, prism_hook_particle_opacity, 75, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook particle opacity")
MACRO_CONFIG_INT(PrismHookParticleSpread, prism_hook_particle_spread, 12, 0, 80, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Particle spread from hook line")
MACRO_CONFIG_INT(PrismHookParticleFade, prism_hook_particle_fade, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fade hook particles over lifetime")
MACRO_CONFIG_INT(PrismHookParticleGlow, prism_hook_particle_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Soft hook particle halo at medium or high quality")
MACRO_CONFIG_INT(PrismHookPulseFrequency, prism_hook_pulse_frequency, 15, 1, 60, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook pulsation frequency in tenths of Hz")
MACRO_CONFIG_INT(PrismHookPulseIntensity, prism_hook_pulse_intensity, 40, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook pulsation intensity; also combines with particle modes")
MACRO_CONFIG_INT(PrismTrail, prism_trail, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player trail: 0 off, 1 line, 2 ribbon, 3 particles")
MACRO_CONFIG_INT(PrismTrailLocal, prism_trail_local, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local player trail")
MACRO_CONFIG_INT(PrismTrailOthers, prism_trail_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other visible player trails")
MACRO_CONFIG_INT(PrismTrailLength, prism_trail_length, 700, 50, 3000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail duration in milliseconds")
MACRO_CONFIG_INT(PrismTrailWidth, prism_trail_width, 5, 1, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail width")
MACRO_CONFIG_INT(PrismTrailInterval, prism_trail_interval, 20, 8, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail sample interval in milliseconds")
MACRO_CONFIG_INT(PrismTrailOpacity, prism_trail_opacity, 55, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail opacity")
MACRO_CONFIG_INT(PrismTrailFade, prism_trail_fade, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fade trails by age")
MACRO_CONFIG_INT(PrismTrailSmoothing, prism_trail_smoothing, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smooth interior trail samples")
MACRO_CONFIG_INT(PrismTrailGlow, prism_trail_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Soft trail halo at medium or high quality")
MACRO_CONFIG_INT(PrismHighlight, prism_highlight, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cosmetic box around normally rendered Tees")
MACRO_CONFIG_INT(PrismHighlightLocal, prism_highlight_local, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Tee highlight")
MACRO_CONFIG_INT(PrismHighlightOthers, prism_highlight_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other visible Tee highlight")
MACRO_CONFIG_INT(PrismHighlightFill, prism_highlight_fill, 12, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight fill opacity")
MACRO_CONFIG_INT(PrismHighlightOpacity, prism_highlight_opacity, 70, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight outline opacity")
MACRO_CONFIG_INT(PrismHighlightWidth, prism_highlight_width, 2, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight outline width")
MACRO_CONFIG_INT(PrismHighlightScale, prism_highlight_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight box scale")
MACRO_CONFIG_INT(PrismHighlightRounding, prism_highlight_rounding, 8, 0, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight corner radius")
MACRO_CONFIG_COL(PrismHookParticleColor, prism_hook_particle_color, 1441600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HookParticleColor (HSL)")
MACRO_CONFIG_COL(PrismTrailColor, prism_trail_color, 1441600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "TrailColor (HSL)")
MACRO_CONFIG_COL(PrismHighlightColor, prism_highlight_color, 1441600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HighlightColor (HSL)")
