// Prism QoL configuration. Intentionally no include guard: DDNet X-macro configuration.
// These settings are deliberately separate from prism_variables.h so visual presets
// cannot silently disable macros, change dummy controls, or rearrange the HUD.
MACRO_CONFIG_INT(PrismDoubleEnabled, prism_double_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Double Tee assistant")
MACRO_CONFIG_INT(PrismDoubleMode, prism_double_mode, 2, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Double Tee: 0 copy, 1 hammer, 2 combined")
MACRO_CONFIG_INT(PrismDoubleInterval, prism_double_interval, 25, 5, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hammer trigger interval in ticks")
MACRO_CONFIG_INT(PrismDoubleBind, prism_double_bind, 0, 0, 512, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Double Tee toggle key (0 unbound)")
MACRO_CONFIG_INT(PrismStopBind, prism_stop_bind, 0, 0, 512, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Emergency stop key (0 unbound, F12 always works)")
MACRO_CONFIG_STR(PrismMacro1, prism_macro_1, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 1 fixed action:delay sequence")
MACRO_CONFIG_INT(PrismMacro1Enabled, prism_macro_1_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable macro 1")
MACRO_CONFIG_INT(PrismMacro1Bind, prism_macro_1_bind, 0, 0, 512, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 1 trigger key")
MACRO_CONFIG_INT(PrismMacro1Mode, prism_macro_1_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 1: once, hold, toggle")
MACRO_CONFIG_STR(PrismMacro2, prism_macro_2, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 2 fixed action:delay sequence")
MACRO_CONFIG_INT(PrismMacro2Enabled, prism_macro_2_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable macro 2")
MACRO_CONFIG_INT(PrismMacro2Bind, prism_macro_2_bind, 0, 0, 512, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 2 trigger key")
MACRO_CONFIG_INT(PrismMacro2Mode, prism_macro_2_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 2: once, hold, toggle")
MACRO_CONFIG_STR(PrismMacro3, prism_macro_3, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 3 fixed action:delay sequence")
MACRO_CONFIG_INT(PrismMacro3Enabled, prism_macro_3_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable macro 3")
MACRO_CONFIG_INT(PrismMacro3Bind, prism_macro_3_bind, 0, 0, 512, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 3 trigger key")
MACRO_CONFIG_INT(PrismMacro3Mode, prism_macro_3_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 3: once, hold, toggle")
MACRO_CONFIG_STR(PrismMacro4, prism_macro_4, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 4 fixed action:delay sequence")
MACRO_CONFIG_INT(PrismMacro4Enabled, prism_macro_4_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable macro 4")
MACRO_CONFIG_INT(PrismMacro4Bind, prism_macro_4_bind, 0, 0, 512, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 4 trigger key")
MACRO_CONFIG_INT(PrismMacro4Mode, prism_macro_4_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Macro 4: once, hold, toggle")
MACRO_CONFIG_INT(PrismHudEnabled, prism_hud_enabled, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable modular Prism HUD")
MACRO_CONFIG_INT(PrismHudHotkeys, prism_hud_hotkeys, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Active Hotkeys HUD module")
MACRO_CONFIG_INT(PrismHudIdentity, prism_hud_identity, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prism name/version HUD module")
MACRO_CONFIG_INT(PrismHudPerformance, prism_hud_performance, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Performance HUD module")
MACRO_CONFIG_INT(PrismHudDummy, prism_hud_dummy, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Dummy Status HUD module")
MACRO_CONFIG_INT(PrismHudStaff, prism_hud_staff, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Server-verified staff HUD module")
MACRO_CONFIG_INT(PrismHudScale, prism_hud_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Modular HUD scale percent")
MACRO_CONFIG_INT(PrismHudOpacity, prism_hud_opacity, 85, 20, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Modular HUD opacity percent")
MACRO_CONFIG_INT(PrismHudHotkeysX, prism_hud_hotkeys_x, 300, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Active Hotkeys normalized X")
MACRO_CONFIG_INT(PrismHudHotkeysY, prism_hud_hotkeys_y, 900, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Active Hotkeys normalized Y")
MACRO_CONFIG_INT(PrismHudIdentityX, prism_hud_identity_x, 300, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prism identity normalized X")
MACRO_CONFIG_INT(PrismHudIdentityY, prism_hud_identity_y, 250, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prism identity normalized Y")
MACRO_CONFIG_INT(PrismHudPerformanceX, prism_hud_performance_x, 8200, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Performance normalized X")
MACRO_CONFIG_INT(PrismHudPerformanceY, prism_hud_performance_y, 250, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Performance normalized Y")
MACRO_CONFIG_INT(PrismHudDummyX, prism_hud_dummy_x, 300, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Dummy normalized X")
MACRO_CONFIG_INT(PrismHudDummyY, prism_hud_dummy_y, 1600, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Dummy normalized Y")
MACRO_CONFIG_INT(PrismHudStaffX, prism_hud_staff_x, 8200, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Staff normalized X")
MACRO_CONFIG_INT(PrismHudStaffY, prism_hud_staff_y, 950, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Staff normalized Y")

// HUD Studio appearance and additional independently positioned widgets.
MACRO_CONFIG_INT(PrismHudBackground, prism_hud_background, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD background")
MACRO_CONFIG_INT(PrismHudPadding, prism_hud_padding, 5, 0, 16, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD padding")
MACRO_CONFIG_INT(PrismHudRounding, prism_hud_rounding, 4, 0, 12, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD rounding")
MACRO_CONFIG_INT(PrismHudFontSize, prism_hud_font_size, 7, 5, 12, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD font size")
MACRO_CONFIG_INT(PrismHudSnap, prism_hud_snap, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD snap")
MACRO_CONFIG_INT(PrismHudGuides, prism_hud_guides, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD guides")
MACRO_CONFIG_INT(PrismHudPreset, prism_hud_preset, 3, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD preset")
MACRO_CONFIG_INT(PrismHudInput, prism_hud_input, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input HUD module")
MACRO_CONFIG_INT(PrismHudInputX, prism_hud_input_x, 300, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input normalized X")
MACRO_CONFIG_INT(PrismHudInputY, prism_hud_input_y, 7500, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input normalized Y")
MACRO_CONFIG_INT(PrismHudEffects, prism_hud_effects, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Effects HUD module")
MACRO_CONFIG_INT(PrismHudEffectsX, prism_hud_effects_x, 7600, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Effects normalized X")
MACRO_CONFIG_INT(PrismHudEffectsY, prism_hud_effects_y, 1800, 0, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Effects normalized Y")
MACRO_CONFIG_INT(PrismHudHotkeysScale, prism_hud_hotkeys_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hotkeys module scale percent")
MACRO_CONFIG_INT(PrismHudIdentityScale, prism_hud_identity_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Identity module scale percent")
MACRO_CONFIG_INT(PrismHudPerformanceScale, prism_hud_performance_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Performance module scale percent")
MACRO_CONFIG_INT(PrismHudDummyScale, prism_hud_dummy_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Dummy module scale percent")
MACRO_CONFIG_INT(PrismHudStaffScale, prism_hud_staff_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Staff module scale percent")
MACRO_CONFIG_INT(PrismHudInputScale, prism_hud_input_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input module scale percent")
MACRO_CONFIG_INT(PrismHudEffectsScale, prism_hud_effects_scale, 100, 65, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Effects module scale percent")
MACRO_CONFIG_INT(PrismInputKeySize, prism_input_key_size, 18, 12, 32, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input key size")
MACRO_CONFIG_INT(PrismInputRounding, prism_input_rounding, 3, 0, 12, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input rounding")
MACRO_CONFIG_INT(PrismInputLabels, prism_input_labels, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input labels")
MACRO_CONFIG_INT(PrismInputAnimation, prism_input_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input animation")
MACRO_CONFIG_COL(PrismInputActiveColor, prism_input_active_color, 4279697288, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Input pressed color")
MACRO_CONFIG_COL(PrismInputInactiveColor, prism_input_inactive_color, 4278190122, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Input released color")
