// Prism visual settings. Intentionally no include guard: DDNet X-macro configuration.
MACRO_CONFIG_INT(PrismEnabled, prism_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Prism visuals")
MACRO_CONFIG_INT(PrismLocalOutline, prism_local_outline, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Tee outline")
MACRO_CONFIG_INT(PrismLocalOutlineWidth, prism_local_outline_width, 2, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Tee outline width")
MACRO_CONFIG_INT(PrismLocalGlow, prism_local_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Tee glow")
MACRO_CONFIG_INT(PrismLocalGlowIntensity, prism_local_glow_intensity, 30, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Tee glow intensity")
MACRO_CONFIG_INT(PrismLocalHook, prism_local_hook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Hook tint")
MACRO_CONFIG_INT(PrismLocalHookGlow, prism_local_hook_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Hook glow")
MACRO_CONFIG_INT(PrismLocalHookIntensity, prism_local_hook_intensity, 30, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local Hook glow intensity")
MACRO_CONFIG_COL(PrismLocalOutlineColor, prism_local_outline_color, 9417407, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local OutlineColor")
MACRO_CONFIG_COL(PrismLocalGlowColor, prism_local_glow_color, 9417407, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local GlowColor")
MACRO_CONFIG_COL(PrismLocalHookColor, prism_local_hook_color, 9417407, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local HookColor")
MACRO_CONFIG_INT(PrismOtherOutline, prism_other_outline, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other Tee outline")
MACRO_CONFIG_INT(PrismOtherOutlineWidth, prism_other_outline_width, 2, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other Tee outline width")
MACRO_CONFIG_INT(PrismOtherGlow, prism_other_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other Tee glow")
MACRO_CONFIG_INT(PrismOtherGlowIntensity, prism_other_glow_intensity, 30, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other Tee glow intensity")
MACRO_CONFIG_INT(PrismOtherHook, prism_other_hook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other Hook tint")
MACRO_CONFIG_INT(PrismOtherHookGlow, prism_other_hook_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other Hook glow")
MACRO_CONFIG_INT(PrismOtherHookIntensity, prism_other_hook_intensity, 30, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other Hook glow intensity")
MACRO_CONFIG_COL(PrismOtherOutlineColor, prism_other_outline_color, 13145023, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other OutlineColor")
MACRO_CONFIG_COL(PrismOtherGlowColor, prism_other_glow_color, 13145023, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other GlowColor")
MACRO_CONFIG_COL(PrismOtherHookColor, prism_other_hook_color, 13145023, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other HookColor")
