// Prism Assist configuration. No include guard: consumed by DDNet config X-macros.
MACRO_CONFIG_INT(PrismHookAssist, prism_hook_assist, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Assist outgoing hook aim only while physical Hook is held")
MACRO_CONFIG_INT(PrismHookFov, prism_hook_fov, 50, 5, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook Assist target field of view in degrees")
MACRO_CONFIG_INT(PrismHookRange, prism_hook_range, 500, 64, 1200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum Hook Assist target distance")
MACRO_CONFIG_INT(PrismHookStrength, prism_hook_strength, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Outgoing hook aim correction strength")
MACRO_CONFIG_INT(PrismHookPrediction, prism_hook_prediction, 3, 0, 12, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target movement lead in ticks")
MACRO_CONFIG_INT(PrismHookDebug, prism_hook_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show physical Hook activation and corrected aim")
MACRO_CONFIG_INT(PrismFreezeAvoid, prism_freeze_avoid, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeze Avoid: off, warning, assist")
MACRO_CONFIG_INT(PrismFreezeHorizon, prism_freeze_horizon, 12, 4, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeze Avoid lookahead in ticks")
MACRO_CONFIG_INT(PrismFreezeDebug, prism_freeze_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Freeze Avoid trajectory debug")
MACRO_CONFIG_INT(PrismPathfinder, prism_pathfinder, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use a physically reachable intent corridor for Freeze Avoid")
MACRO_CONFIG_INT(PrismPathHorizon, prism_path_horizon, 100, 50, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Local route horizon in physics ticks")
MACRO_CONFIG_INT(PrismPathBudget, prism_path_budget, 1500, 250, 4000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Planner soft deadline in microseconds; fallback on expiry")
MACRO_CONFIG_INT(PrismPathDebug, prism_path_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show intent corridor, waypoint, confidence, recovery and timing")
MACRO_CONFIG_INT(PrismAimHammer, prism_aim_hammer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Hammer outgoing aim assistance")
MACRO_CONFIG_INT(PrismAimHammerActivation, prism_aim_hammer_activation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Activation: physical Fire or always")
MACRO_CONFIG_INT(PrismAimHammerFov, prism_aim_hammer_fov, 30, 5, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Acquisition field of view in degrees")
MACRO_CONFIG_INT(PrismAimHammerRange, prism_aim_hammer_range, 72, 16, 96, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum acquisition distance")
MACRO_CONFIG_INT(PrismAimHammerPrediction, prism_aim_hammer_prediction, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Motion prediction strength percent")
MACRO_CONFIG_INT(PrismAimHammerCorrection, prism_aim_hammer_correction, 8, 1, 45, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum outgoing angular correction per input")
MACRO_CONFIG_INT(PrismAimHammerSmoothing, prism_aim_hammer_smoothing, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim interpolation strength percent")
MACRO_CONFIG_INT(PrismAimHammerPriority, prism_aim_hammer_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target priority: closest aim or nearest distance")
MACRO_CONFIG_INT(PrismAimHammerDebug, prism_aim_hammer_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show weapon solver output")
MACRO_CONFIG_INT(PrismAimGun, prism_aim_gun, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Gun outgoing aim assistance")
MACRO_CONFIG_INT(PrismAimGunActivation, prism_aim_gun_activation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Activation: physical Fire or always")
MACRO_CONFIG_INT(PrismAimGunFov, prism_aim_gun_fov, 30, 5, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Acquisition field of view in degrees")
MACRO_CONFIG_INT(PrismAimGunRange, prism_aim_gun_range, 700, 16, 1600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum acquisition distance")
MACRO_CONFIG_INT(PrismAimGunPrediction, prism_aim_gun_prediction, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Motion prediction strength percent")
MACRO_CONFIG_INT(PrismAimGunCorrection, prism_aim_gun_correction, 8, 1, 45, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum outgoing angular correction per input")
MACRO_CONFIG_INT(PrismAimGunSmoothing, prism_aim_gun_smoothing, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim interpolation strength percent")
MACRO_CONFIG_INT(PrismAimGunPriority, prism_aim_gun_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target priority: closest aim or nearest distance")
MACRO_CONFIG_INT(PrismAimGunDebug, prism_aim_gun_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show weapon solver output")
MACRO_CONFIG_INT(PrismAimShotgun, prism_aim_shotgun, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Shotgun outgoing aim assistance")
MACRO_CONFIG_INT(PrismAimShotgunActivation, prism_aim_shotgun_activation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Activation: physical Fire or always")
MACRO_CONFIG_INT(PrismAimShotgunFov, prism_aim_shotgun_fov, 30, 5, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Acquisition field of view in degrees")
MACRO_CONFIG_INT(PrismAimShotgunRange, prism_aim_shotgun_range, 700, 16, 1600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum acquisition distance")
MACRO_CONFIG_INT(PrismAimShotgunPrediction, prism_aim_shotgun_prediction, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Motion prediction strength percent")
MACRO_CONFIG_INT(PrismAimShotgunCorrection, prism_aim_shotgun_correction, 8, 1, 45, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum outgoing angular correction per input")
MACRO_CONFIG_INT(PrismAimShotgunSmoothing, prism_aim_shotgun_smoothing, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim interpolation strength percent")
MACRO_CONFIG_INT(PrismAimShotgunPriority, prism_aim_shotgun_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target priority: closest aim or nearest distance")
MACRO_CONFIG_INT(PrismAimShotgunDebug, prism_aim_shotgun_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show weapon solver output")
MACRO_CONFIG_INT(PrismAimGrenade, prism_aim_grenade, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Grenade outgoing aim assistance")
MACRO_CONFIG_INT(PrismAimGrenadeActivation, prism_aim_grenade_activation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Activation: physical Fire or always")
MACRO_CONFIG_INT(PrismAimGrenadeFov, prism_aim_grenade_fov, 30, 5, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Acquisition field of view in degrees")
MACRO_CONFIG_INT(PrismAimGrenadeRange, prism_aim_grenade_range, 600, 16, 1600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum acquisition distance")
MACRO_CONFIG_INT(PrismAimGrenadePrediction, prism_aim_grenade_prediction, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Motion prediction strength percent")
MACRO_CONFIG_INT(PrismAimGrenadeCorrection, prism_aim_grenade_correction, 8, 1, 45, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum outgoing angular correction per input")
MACRO_CONFIG_INT(PrismAimGrenadeSmoothing, prism_aim_grenade_smoothing, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim interpolation strength percent")
MACRO_CONFIG_INT(PrismAimGrenadePriority, prism_aim_grenade_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target priority: closest aim or nearest distance")
MACRO_CONFIG_INT(PrismAimGrenadeDebug, prism_aim_grenade_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show weapon solver output")
MACRO_CONFIG_INT(PrismAimLaser, prism_aim_laser, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Laser outgoing aim assistance")
MACRO_CONFIG_INT(PrismAimLaserActivation, prism_aim_laser_activation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Activation: physical Fire or always")
MACRO_CONFIG_INT(PrismAimLaserFov, prism_aim_laser_fov, 30, 5, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Acquisition field of view in degrees")
MACRO_CONFIG_INT(PrismAimLaserRange, prism_aim_laser_range, 800, 16, 1600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum acquisition distance")
MACRO_CONFIG_INT(PrismAimLaserPrediction, prism_aim_laser_prediction, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Motion prediction strength percent")
MACRO_CONFIG_INT(PrismAimLaserCorrection, prism_aim_laser_correction, 8, 1, 45, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum outgoing angular correction per input")
MACRO_CONFIG_INT(PrismAimLaserSmoothing, prism_aim_laser_smoothing, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim interpolation strength percent")
MACRO_CONFIG_INT(PrismAimLaserPriority, prism_aim_laser_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target priority: closest aim or nearest distance")
MACRO_CONFIG_INT(PrismAimLaserDebug, prism_aim_laser_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show weapon solver output")
MACRO_CONFIG_INT(PrismAimLaserBounce, prism_aim_laser_bounce, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Search bounded single-bounce laser shots and confirm in prediction")
MACRO_CONFIG_INT(PrismUnfreezeSelf, prism_unfreeze_self, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Preemptive laser bounce self-unfreeze; never fire while frozen")
MACRO_CONFIG_INT(PrismUnfreezeOthers, prism_unfreeze_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Confirm hammer or laser rescue of frozen teammates")
MACRO_CONFIG_INT(PrismUnfreezeActivation, prism_unfreeze_activation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Other unfreeze activation: physical Fire or automatic")
MACRO_CONFIG_INT(PrismUnfreezeFov, prism_unfreeze_fov, 45, 5, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Unfreeze shot field of view in degrees")
MACRO_CONFIG_INT(PrismUnfreezeRange, prism_unfreeze_range, 800, 32, 1600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum teammate rescue distance")
MACRO_CONFIG_INT(PrismUnfreezePriority, prism_unfreeze_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen teammate priority: closest aim or nearest")
MACRO_CONFIG_INT(PrismUnfreezeCooldown, prism_unfreeze_cooldown, 40, 5, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Minimum ticks between confirmed automatic rescue shots")
MACRO_CONFIG_INT(PrismUnfreezeDebug, prism_unfreeze_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show verified rescue action and prediction cost")
